version: "3.3"
services:
  plot:
    container_name: 'matplotlib_seaborn'
    command: bash -c "jupyter lab --notebook-dir=/home/matplotlib_seaborn --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
    build: .
    ports:
      - '8888:8888'
    volumes:
      - ../:/home/matplotlib_seaborn